on: workflow_dispatch

jobs:
  check-pods:
    runs-on: ubuntu-latest
    steps:
    - name: Connect to K3s host
      run: |
        mkdir ~/.ssh
        eval `ssh-agent -s`
        ssh-add <<< "${{ secrets.SSH_KEY }}"
        ssh-keyscan -p 32510 ${{ secrets.JUMP_HOST }} >> ~/.ssh/known_hosts
        ssh -p 32510 ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST}} "echo 'Hello from Bastion'"
    
